# Generated by Django 4.2.7 on 2023-11-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbsQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=250)),
                ("pub_date", models.DateField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="CardioQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=250)),
                ("pub_date", models.DateField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="PilatesQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=250)),
                ("pub_date", models.DateField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="StrengthTrainingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=250)),
                ("pub_date", models.DateField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="StretchQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=250)),
                ("pub_date", models.DateField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="YogaQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=250)),
                ("pub_date", models.DateField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="YogaAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.BooleanField(default=False)),
                ("duration", models.DurationField()),
                ("video", models.CharField(default="", max_length=250)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.stretchquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StretchAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.BooleanField(default=False)),
                ("duration", models.DurationField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.stretchquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StrenghtTrainingAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("PL", "Pull"),
                            ("PS", "Push"),
                            ("LG", "Legs"),
                            ("SH", "Shoulders"),
                            ("CH", "Chest"),
                            ("BK", "Back"),
                            ("AR", "Arms"),
                            ("NO", "None"),
                        ],
                        max_length=2,
                    ),
                ),
                ("duration", models.DurationField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.strengthtrainingquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PilatesAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.BooleanField(default=False)),
                ("duration", models.DurationField()),
                ("video", models.CharField(default="", max_length=250)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.stretchquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CardioAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("WK", "Walking"),
                            ("RN", "Running"),
                            ("SM", "Stairmaster"),
                            ("BK", "Bike"),
                            ("NO", "None"),
                        ],
                        max_length=2,
                    ),
                ),
                ("duration", models.DurationField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.cardioquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbsAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.BooleanField(default=False)),
                ("duration", models.DurationField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.absquestion",
                    ),
                ),
            ],
        ),
    ]
